#Base Screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
#Asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
#Player
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
SHOT_RADIUS = 5
#By the power of omnisiah
#All cooldowns for weapons must be x2 more than intended
#Weapons
    #Melta
MELTA_COOLDOWN = 2.0
MELTA_SPEED = 350
MELTA_MAX_RANGE = int(SCREEN_WIDTH / 4)
    #MCH_Gun
MCH_GUN_COOLDOWN = 0.5
MCH_GUN_SPEED = 500
    #RailGun
RAILGUN_COOLDOWN = 1.2
RAILGUN_SPEED = 1200
    #Granade Launcher
G_LAUNCHER_COOLDOWN = 2.0
G_LAUNCHER_RELOAD = 6
G_LAUNCHER_SPEED = 420
G_LAUNCHER_AMMO = 5
G_LAUNCHER_AOE = 150
G_LAUNCHER_LIFETIME = 0.3
MAX_G_LAUNCHER_RANGE = int(SCREEN_WIDTH / 3)
#Version
GAME_VERSION = 1.2